# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebf2277132fe65b980b0defc353d957d36d2ffa683558b128afdc80eb31beff7138bcba8f22fc106ddddbeef0b674480ee7e7e469dc75137147c7a01c6303a30
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
test:
  secret_key_base: 5ad3f3ab0790dd6db21ca906ad54f1560738be59da25ae6d0d47a8eb48cc7fdd5ff1adaf5b41f77bf1d9478336154ff54284c5ebe608aad2d94255bc08b13f3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
